spring:
  application:
    name: feedback-online-prod

  # Database (Neon PostgreSQL)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000

  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: false

  # Mail Service (Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Config ứng dụng (Frontend URL & JWT)
application:
  frontend:
    url: ${FRONTEND_URL}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
      refresh-token-expiration: 604800000

# Logging Production
logging:
  level:
    root: info
    com.josephhieu.feedbackonline: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

# API Docs (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html