-- Kích hoạt extension UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. ADMIN
CREATE TABLE "ADMIN" (
    "Username" VARCHAR(50) PRIMARY KEY,
    "Password" VARCHAR(255) NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TOPIC
CREATE TABLE "TOPIC" (
    "MaTopic" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TenTopic" VARCHAR(255) NOT NULL,
    "Status" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. TRAINER
CREATE TABLE "TRAINER" (
    "MaTrainer" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TenTrainer" VARCHAR(255) NOT NULL,
    "Status" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. TEMPLATE
CREATE TABLE "TEMPLATE" (
    "MaTemplate" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TenTemplate" VARCHAR(255) NOT NULL,
    "Status" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. LOP
CREATE TABLE "LOP" (
    "MaLop" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TenLop" VARCHAR(255) NOT NULL,
    "MaTemplate" UUID REFERENCES "TEMPLATE"("MaTemplate"),
    "Status" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. HOCVIEN
CREATE TABLE "HOCVIEN" (
    "MaHocVien" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TenHocVien" VARCHAR(255) NOT NULL,
    "Password" VARCHAR(255) NOT NULL,
    "MaLop" UUID REFERENCES "LOP"("MaLop"),
    "Status" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. GANTOPIC
CREATE TABLE "GANTOPIC" (
    "MaGanTopic" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "MaLop" UUID REFERENCES "LOP"("MaLop"),
    "MaTrainer" UUID REFERENCES "TRAINER"("MaTrainer"),
    "MaTopic" UUID REFERENCES "TOPIC"("MaTopic"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. CAUHOI
CREATE TABLE "CAUHOI" (
    "MaCauHoi" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "MaTemplate" UUID REFERENCES "TEMPLATE"("MaTemplate"),
    "TenCauHoi" TEXT NOT NULL,
    "DiemToiThieu" INTEGER DEFAULT 1,
    "DiemToiDa" INTEGER DEFAULT 5,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 9. FEEDBACK
CREATE TABLE "FEEDBACK" (
    "MaFeedback" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "MaLop" UUID REFERENCES "LOP"("MaLop"),
    "MaTemplate" UUID REFERENCES "TEMPLATE"("MaTemplate"),
    "MaHocVien" UUID REFERENCES "HOCVIEN"("MaHocVien"),
    "MaTopic" UUID REFERENCES "TOPIC"("MaTopic"),
    "MaTrainer" UUID REFERENCES "TRAINER"("MaTrainer"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. CHITIETFEEDBACK
CREATE TABLE "CHITIETFEEDBACK" (
    "MaFeedback" UUID REFERENCES "FEEDBACK"("MaFeedback"),
    "MaCauHoi" UUID REFERENCES "CAUHOI"("MaCauHoi"),
    "Diem" INTEGER NOT NULL,
    "GhiChu" TEXT,
    PRIMARY KEY ("MaFeedback", "MaCauHoi")
);